### ISSUE TITLE
Are you using GNU's code?

### ISSUE THREAD

**Issue by JaydenDev** [hello-smile6/custom-c-utils#2]
Are you using GNU's code? If not, just close this issue. If you are, to be safe do the following:

- Use the same license
- Give credit to the devs

**Comment by hello-smile6** [comment]
> Are you using GNU's code? If not, just close this issue. If you are, to be safe do the following:
> 
> * Use the same license
> * Give credit to the devs

No, I'm going to use GPLv3 though

**Comment by JaydenDev** [comment]
> > Are you using GNU's code? If not, just close this issue. If you are, to be safe do the following:
> > 
> > * Use the same license
> > * Give credit to the devs
> 
> No, I'm going to use GPLv3 though

A... more free license... would be nice. But it's your choice!

**Comment by hello-smile6** [comment]
> > > Are you using GNU's code? If not, just close this issue. If you are, to be safe do the following:
> > > 
> > > * Use the same license
> > > * Give credit to the devs
> > 
> > 
> > No, I'm going to use GPLv3 though
> 
> A... more free license... would be nice. But it's your choice!

What license?
